"""Budgeted data collection with simulator branching.

Main trajectories are generated by a history-based behavior policy. At a
branch point (after observing o_t) the collector snapshots the privileged
simulator state and, for every first action, rolls out up to `horizon` steps
with a uniform continuation policy, restoring the snapshot in between. Every
branch step is charged to the same ledger as the main trajectory.

Random streams are separated so that branching never changes the main
trajectory: the environment RNG is part of the snapshot and is restored,
behavior actions use `actor_rng`, and branch decisions/continuations use
`branch_rng`.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Callable, List, Optional, Tuple

from .accounting import MeteredSimulator, TransitionLedger
from .data import Branch, Episode, EvaluatorLabel, EvaluatorLabels, History
from .env import (
    ACT_FORWARD,
    ACT_LEFT,
    ACT_RIGHT,
    N_ACTIONS,
    OBS_JUNCTION,
    AliasedTMaze,
    MazeConfig,
)
from .splits import derive_seed, episode_id, episode_seed

Policy = Callable[[History, random.Random], int]


@dataclass(frozen=True)
class CollectConfig:
    budget: int  # hard cap on env transitions, branches included
    horizon: int  # branch rollout length k
    branch_prob: float  # probability of a branch set at each main step
    behavior_forward_prob: float = 0.8
    max_episodes: Optional[int] = None

    def __post_init__(self) -> None:
        if self.budget < 0 or self.horizon < 1:
            raise ValueError("need budget >= 0 and horizon >= 1")
        if not 0.0 <= self.branch_prob <= 1.0:
            raise ValueError("branch_prob must be in [0, 1]")

    @property
    def branch_set_cost_bound(self) -> int:
        return N_ACTIONS * self.horizon


def make_behavior_policy(forward_prob: float) -> Policy:
    """Uniform at the junction; mostly FORWARD elsewhere. Reads only o_t."""

    def policy(history: History, rng: random.Random) -> int:
        if history.observations[-1] == OBS_JUNCTION:
            return rng.randrange(N_ACTIONS)
        if rng.random() < forward_prob:
            return ACT_FORWARD
        return rng.choice((ACT_LEFT, ACT_RIGHT))

    return policy


def continuation_action(rng: random.Random) -> int:
    return rng.randrange(N_ACTIONS)


@dataclass
class CollectResult:
    episodes: Tuple[Episode, ...]
    labels: EvaluatorLabels  # evaluator-only; never passed to training code
    ledger: dict
    stats: dict


def _branch_set(
    sim: MeteredSimulator, t: int, horizon: int, rng: random.Random
) -> List[Branch]:
    snap = sim.snapshot()
    branches = []
    for first_action in range(N_ACTIONS):
        sim.restore(snap)
        acts, obs, rews = [], [], []
        terminated = truncated = False
        action = first_action
        for j in range(horizon):
            if j > 0:
                action = continuation_action(rng)
            o, r, terminated, truncated = sim.step(action, kind="branch")
            acts.append(action)
            obs.append(o)
            rews.append(r)
            if terminated or truncated:
                break
        branches.append(
            Branch(t, tuple(acts), tuple(obs), tuple(rews), terminated, truncated)
        )
    sim.restore(snap)
    return branches


def collect_split(
    maze_cfg: MazeConfig,
    cfg: CollectConfig,
    run_seed: int,
    split: str,
    behavior: Optional[Policy] = None,
) -> CollectResult:
    ledger = TransitionLedger(cap=cfg.budget, label=f"{split}:collect")
    sim = MeteredSimulator(AliasedTMaze(maze_cfg), ledger)
    policy = behavior or make_behavior_policy(cfg.behavior_forward_prob)
    actor_rng = random.Random(derive_seed("actor", run_seed, split))
    branch_rng = random.Random(derive_seed("branch", run_seed, split))

    episodes: List[Episode] = []
    labels: EvaluatorLabels = {}
    skipped_branch_sets = 0
    index = 0
    while ledger.remaining() > 0:
        if cfg.max_episodes is not None and index >= cfg.max_episodes:
            break
        eid = episode_id(run_seed, split, index)
        obs = sim.reset(episode_seed(run_seed, split, index))
        gt = sim.evaluator_ground_truth()
        labels[eid] = EvaluatorLabel(
            eid, gt["clue"], gt["corridor_len"], gt["optimal_arm"]
        )
        history = History.start(obs)
        branches: List[Branch] = []
        terminated = truncated = budget_truncated = False
        while not (terminated or truncated):
            if ledger.remaining() <= 0:
                budget_truncated = True
                break
            if cfg.branch_prob > 0.0 and branch_rng.random() < cfg.branch_prob:
                # Keep one step in reserve for the main transition itself.
                if ledger.remaining() >= cfg.branch_set_cost_bound + 1:
                    branches.extend(
                        _branch_set(sim, history.t, cfg.horizon, branch_rng)
                    )
                else:
                    skipped_branch_sets += 1
            action = policy(history, actor_rng)
            obs, reward, terminated, truncated = sim.step(action, kind="main")
            history = history.extend(action, obs, reward)
        episodes.append(
            Episode(
                episode_id=eid,
                split=split,
                observations=history.observations,
                actions=history.actions,
                rewards=history.rewards,
                terminated=terminated,
                truncated=truncated,
                budget_truncated=budget_truncated,
                branches=tuple(branches),
            )
        )
        index += 1

    stats = {
        "episodes": len(episodes),
        "branch_sets": sum(len(e.branches) for e in episodes) // N_ACTIONS,
        "branch_sets_skipped_for_budget": skipped_branch_sets,
        "budget_truncated_episodes": sum(e.budget_truncated for e in episodes),
        "timeout_episodes": sum(e.truncated for e in episodes),
        "terminated_episodes": sum(e.terminated for e in episodes),
    }
    return CollectResult(tuple(episodes), labels, ledger.summary(), stats)
